name: Employee AI CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  backend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest || true

  frontend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Packages
        run: npm install

      - name: Build Frontend
        run: npm run build

  deploy:
    needs:
      - backend-test
      - frontend-build

    runs-on: ubuntu-latest

    steps:
      - name: Deployment Successful
        run: echo "Render and Vercel auto-deploy triggered."